service: crud-api
frameworkVersion: '3'

package:
  exclude:
    - node_modules

custom:
  tableName: '${opt:stage, self:provider.stage}'

provider:
  name: aws
  runtime: nodejs18.x
  stage: develop
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
            - dynamodb:DescribeTable
            - dynamodb:BatchWriteItem
          Resource: 
            - "arn:aws:dynamodb:us-east-1:*:table/*"
        - Effect: Allow
          Action:
            - execute-api:Invoke
          Resource: '*'


functions:
  createOrganization:
    handler: components/organization/organizationController.createOrganization
    timeout: 30
    events:
      - httpApi:
          path: /organization
          method: post
